### ISSUE TITLE
MultiFrame script update for Automatic 1.6

### ISSUE THREAD

**Issue by KiryuKazzy** [finefin/SD-scripts#2]
Unfortunately, the script doesn't work on the new version of SD :(

**Comment by finefin** [comment]
I am using it with the vladmandic fork and see no problems or errors.
Can you elaborate what isn't working exactly and ideally post the log output?

**Comment by KiryuKazzy** [comment]
> I am using it with the vladmandic fork and see no problems or errors. Can you elaborate what isn't working exactly and ideally post the log output?
> 
> EDIT: I see there's an update for vladmandic as well. I'll test the script with that new version now...

I'm using the script with the version from Automatic1111, the version from Vladmandic I don't really like the interface :) I'll send you the logs later

**Comment by finefin** [comment]
I am using the script with the latest version of... let's call it "vladmandic1111" - and it works fine for me. 

As for the interface: just switch to a different UI theme! I also do not like the default UI and chose one that is closer to the automatic theme.

**Comment by alexbofa** [comment]
Hello, I have problem with Automatic1111 1.6.0
```bat
*** Error completing request
    Traceback (most recent call last):
      File "E:\Stable-Diffusion\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\Stable-Diffusion\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\Stable-Diffusion\modules\img2img.py", line 202, in img2img
        process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "E:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 25, in img2img_process_batch_hijack
        return getattr(img2img, '__controlnet_original_process_batch')(p, *args, **kwargs)
      File "E:\Stable-Diffusion\modules\img2img.py", line 107, in process_batch
        proc = modules.scripts.scripts_img2img.run(p, *args)
      File "E:\Stable-Diffusion\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "E:\Stable-Diffusion\scripts\multi_frame_render-beta-fine-version.py", line 69, in run
        shared.log.info(f"=======> p.n_iter={p.n_iter} use_nth_frame={use_nth_frame} batch_count={batch_count} loops={loops}")
    AttributeError: module 'modules.shared' has no attribute 'log'
```

**Comment by finefin** [comment]
please try again

**Comment by alexbofa** [comment]
> please try again

Thank you, the error is gone
